# Generated by Django 4.0.6 on 2023-04-05 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customer_addrees1_alter_customer_city_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Food',
        ),
    ]
